src/Entity/Set.php
<?php

namespace App\Entity;

use App\Repository\SetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SetRepository::class)
 * @ORM\Table(name="card_set")
 */
class Set
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $code;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $released_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $icon;

    /**
     * @ORM\OneToMany(targetEntity=Card::class, mappedBy="set", orphanRemoval=true)
     */
    private $cards;

    private $iconSvgURI;

    public function __construct()
    {
        $this->cards = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getReleasedAt(): ?\DateTimeImmutable
    {
        return $this->released_at;
    }

    public function setReleasedAt(\DateTimeImmutable $released_at): self
    {
        $this->released_at = $released_at;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function getIconSvgURI(): string
    {
        return $this->iconSvgURI;
    }

    public function setIcon(string $icon): self
    {
        $this->icon = $icon;

        return $this;
    }

    /**
     * @return Collection<int, Card>
     */
    public function getCards(): Collection
    {
        return $this->cards;
    }

    public function addCard(Card $card): self
    {
        if (!$this->cards->contains($card)) {
            $this->cards[] = $card;
            $card->setSet($this);
        }

        return $this;
    }

    public function removeCard(Card $card): self
    {
        if ($this->cards->removeElement($card)) {
            // set the owning side to null (unless already changed)
            if ($card->getSet() === $this) {
                $card->setSet(null);
            }
        }

        return $this;
    }

    public function setIconSvgURI(string $uri): self
    {
        $this->iconSvgURI = $uri;
        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

}

templates/pages/collection.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cards available{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <h1>Cards</h1>

        {{ form_start(form) }}
        {{ form_end(form) }}

        {% if cards[0] is defined %}
            <h3>Here are the cards from {{ cards[0].set.name }}</h3>

            {% for card in cards %}
                <div>
                    <img src="../cards/{{ card.image }}.png" alt="No image found" height="300px">
                    <div>
                        <h4>{{ card.name }}</h4>
                        <p>Type : {{ card.type }}</p>
                        {% set colors = translate_colors(card.color) %}
                        {% if colors is not empty %}
                            {% if ',' in colors %}
                                <p>Colors : {{ colors }}</p>
                            {% else %}
                                <p>Color : {{ colors }}</p>
                            {% endif %}
                        {% endif %}
                        {% if card.description is defined and card.description is not empty %}
                            <p>Description : {{ card.description }}</p>
                        {% endif %}
                        <p>Artist : {{ card.artist }}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h3>No card found !</h3>
        {% endif %}
    </div>
{% endblock %}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Collections available{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Collections</h1>

    <h3>Click on a collection to see the cards in it</h3>

    {% for set in sets %}
        <div>
            <img src="sets/{{ set.icon }}.svg" alt="No image found" height="75px">
            <div>
                <h4>{{ set.name }}</h4>
                <p>Released on the {{ set.releasedAt | date('d/m/Y') }}</p>
                <p>Code : {{ set.code }}</p>
                <p>This collection has <a href="{{ path('collection_detail', {'id': set.id}) }}">{{ set.cards | length }} cards</a> in it</p>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}